#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

wmname LG3D

bspc monitor eDP-1-1 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a Android_Studio state=tiled
